name: Update All Rules from SRC_rulesets

on:
  schedule:
    # 每2天 UTC 时间 02:00 运行
    - cron: '0 2 */2 * *'
  workflow_dispatch:
    # 允许手动触发工作流
    
permissions:
  contents: write

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Scripts/requirements.txt

      - name: Run Python script to merge Net rules
        run: |
          python Scripts/rulesets_merge/manufacture.py
      
      - name: Run Python script to convert Dforked rules
        run: |
          python Scripts/forked_rulesets_get/list2yaml.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add Generated_rulesets/*.yaml
          git add Generated_rulesets/*.json
          git add SRC_rulesets/Forked_rulesets/Converted_rulesets/*.yaml
          git commit -m "Auto-update rules" || echo "No changes to commit"
          # 使用 GITHUB_TOKEN 进行认证
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}